version: '3.3'
services:
  stirling-pdf:
    container_name: Stirling-PDF-Staging
    image: frooodle/s-pdf:latest
    deploy:
      resources:
        limits:
          memory: 2G  # Reduced memory for staging
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -q 'Please sign in'"]
      interval: 10s  # Increased interval for staging
      timeout: 15s  # Increased timeout for staging
      retries: 5  # Reduced retries for staging
    ports:
      - "8081:8080" 
    volumes:
      - /stirling/staging/data:/usr/share/tessdata:rw
      - /stirling/staging/config:/configs:rw
      - /stirling/staging/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "true"
      SECURITY_ENABLELOGIN: "true"
      PUID: 1002
      PGID: 1002
      UMASK: "022"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: Stirling-PDF-Staging
      UI_HOMEDESCRIPTION: Staging site for Stirling-PDF Latest with Security
      UI_APPNAMENAVBAR: Stirling-PDF Staging
      SYSTEM_MAXFILESIZE: "50" 
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "false"  
    restart: on-failure:3  
